# Generated by Django 3.1.7 on 2022-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_email',
            field=models.EmailField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
